services:
  java-app:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: java-app
    ports:
      - "${SPRING_PORT}:3000"
    volumes:
      - ./java/app:/home/gradle/project
    environment:
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_REDIRECT_URI=${AUTH0_REDIRECT_URI}
      - AUTH0_ISSUER_URI=${AUTH0_ISSUER_URI}
      - SPRING_PORT=${SPRING_PORT}

  python-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python-app
    volumes:
      - ./python:/app
    environment:
      - REDIS_HOST=clustercfg.demo-cluster.faysnd.euw2.cache.amazonaws.com
      - REDIS_PORT=6379
      - REDIS_SSL=True

volumes:
  redis_data:
