services:
  java-app:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: java-app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./java/app:/home/gradle/project
      - gradle-cache:/home/gradle/.gradle

  python-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python-app
    expose:
      - "8000"
    ports:
      - "5001:8000"
    volumes:
      - ./python:/app

volumes:
  gradle-cache:
