
services:
  java-app:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: java-app
    ports:
      - "${SPRING_PORT}:3000"
    volumes:
      - ./java/app:/home/gradle/project
    environment:
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_REDIRECT_URI=${AUTH0_REDIRECT_URI}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_SCOPE=${AUTH0_SCOPE}
      - AUTH0_ISSUER_URI=${AUTH0_ISSUER_URI}
      - SPRING_PORT=${SPRING_PORT}

  python-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python-app
    volumes:
      - ./python:/app
    ports:
      - "5001:8000"

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: