version: "3.9"

services:
  gradle:
    build: .
    container_name: gradle-builder
    user: gradle
    volumes:
      - ./app:/home/gradle/project
      - gradle-cache:/home/gradle/.gradle
    working_dir: /home/gradle/project
    command: gradle build

volumes:
  gradle-cache:
