services:
  java-app:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: java-app
    ports:
      - "${SPRING_PORT}:3000"
    volumes:
      - ./java/app:/home/gradle/project
    environment:
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
      - SPRING_PORT=${SPRING_PORT}

  python-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python-app
    volumes:
      - ./python:/app
