services:
  gradle:
    build: .
    container_name: gradle-builder
    user: root
    volumes:
      - ./app:/home/gradle/project
      - gradle-cache:/home/gradle/.gradle
    working_dir: /home/gradle/project
    ports:
      - "8080:8080"


volumes:
  gradle-cache:
