server:
  port: ${SPRING_PORT:3000}  # default to 3000 if not set

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.java_server.shop: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
          audience: ${AUTH0_AUDIENCE}

auth0:
  domain: ${AUTH0_DOMAIN}
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  redirect-uri: ${AUTH0_REDIRECT_URI}
  scope: ${AUTH0_SCOPE:openid profile email scrape:read}
