FROM gradle:9.0.0-jdk17 AS build
WORKDIR /home/gradle/project
COPY . ./
RUN gradle clean bootJar --no-daemon

FROM eclipse-temurin:17-jdk
WORKDIR /app

COPY --from=build /home/gradle/project/app/build/libs/app.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
