spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Auth0
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI}

server:
  port: ${SPRING_PORT}
